export const ALERT_TYPE_INFO = "ALERT_TYPE_INFO";
export const ALERT_TYPE_SUCCESS = "ALERT_TYPE_SUCCESS";
export const ALERT_TYPE_WARNNG = "ALERT_TYPE_WARNNG";
export const ALERT_TYPE_ERROR = "ALERT_TYPE_ERROR";