
export const RESPONSE_LOGIN_REQUEST = "login_request";
export const RESPONSE_LOGIN_SUCCESS = "login_success";
export const RESPONSE_LOGIN_FAILURE = "login_failure";

export const RESPONSE_REGISTER_USER_REQUEST = "register_request";
export const RESPONSE_REGISTER_USER_SUCCESS = "register_success";
export const RESPONSE_REGISTER_USER_FAILURE = "register_failure";

export const RESPONSE_SAVE_USER_CATEGORIES_REQUEST = "RESPONSE_SAVE_USER_CATEGORIES_REQUEST";
export const RESPONSE_SAVE_USER_CATEGORIES_SUCCESS = "RESPONSE_SAVE_USER_CATEGORIES_SUCCESS";
export const RESPONSE_SAVE_USER_CATEGORIES_FAILURE = "RESPONSE_SAVE_USER_CATEGORIES_FAILURE";
